<?xml version="1.0"?>

<!DOCTYPE pizza [
	<!ELEMENT tms (database, logs)>

	<!ELEMENT database (dbdriver, dburl, dbuser, dbpasswd, dbminconn, dbmaxconn)>
	<!ELEMENT dbdriver (#PCDATA)>
	<!ELEMENT dburl (#PCDATA)>
	<!ELEMENT dbuser (#PCDATA)>
	<!ELEMENT dbpasswd (#PCDATA)>
	<!ELEMENT dbminconn (#PCDATA)>
	<!ELEMENT dbmaxconn (#PCDATA)>

	<!ELEMENT logs (logconn, logsize)>
	<!ELEMENT logconn (#PCDATA)>
	<!ELEMENT logsize (#PCDATA)>

	<!ELEMENT format (fordate, fordecimal, forcurrency)>
	<!ELEMENT fordate (#PCDATA)>
	<!ELEMENT fordecimal (#PCDATA)>
	<!ELEMENT forcurrency (#PCDATA)>

]>

<tms>

    <database>
        <dbdriver>com.mysql.jdbc.Driver</dbdriver>
        <dburl>jdbc:mysql://localhost:3306/dimata_testing</dburl>
        <dbuser>root</dbuser>
        <dbpasswd>root</dbpasswd>

        <dbminconn>2</dbminconn>
        <dbmaxconn>30</dbmaxconn>
    </database>

    <logs>
        <logconn>tmsconn.log</logconn>
        <logapp>tmsapp.log</logapp>
        <logsize>5</logsize>
    </logs>

    <format>
        <fordate>MMM-dd-yyyy</fordate>
        <fordecimal>###,###.############</fordecimal>
        <forcurrency>###,###.00</forcurrency>
    </format>

</tms>
